import React from "react";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Case Study</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.google.com/favicon.ico" />
      </Head>
      <div className="shadow-xl mt-32 p-10 text-gray-700 rounded-lg">
        <h1 className="text-4xl font-bold">
          Welcome to the Case Study App
        </h1>
      </div>
    </>
  );
};

export default Home;
